export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();

  const { gameData, plays, email, teamName, opponentName, gameDate } = req.body;

  try {
    // Generate game summary using Claude
    const homeTeam = gameData?.homeTeam;
    const awayTeam = gameData?.awayTeam;

    const summaryPrompt = `You are Honus, a 1920s baseball announcer. Write a short exciting post-game summary (3-4 sentences) for this game:
${awayTeam?.name || "Away"} ${awayTeam?.runs || 0} - ${homeTeam?.name || "Home"} ${homeTeam?.runs || 0}
Date: ${gameDate || "Today"}
Key plays: ${plays?.slice(-5).map(p => p.description).join(", ") || "No plays recorded"}
Make it dramatic and fun like a 1920s radio broadcast!`;

    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5",
        max_tokens: 200,
        messages: [{ role: "user", content: summaryPrompt }],
      }),
    });

    const claudeData = await claudeRes.json();
    const summary = claudeData.content?.[0]?.text || "Great game today!";

    // Build stats table for email
    const battingStats = {};
    if (plays && plays.length > 0) {
      plays.forEach(play => {
        const desc = play.description || "";
        const playerMatch = desc.match(/^([A-Z]\.\s\w+|\w+\s\w+)/);
        if (!playerMatch) return;
        const player = playerMatch[1];
        if (!battingStats[player]) {
          battingStats[player] = { ab: 0, h: 0, rbi: 0, bb: 0, k: 0 };
        }
        const d = desc.toLowerCase();
        if (d.includes("home run") || d.includes("double") || d.includes("triple") || d.includes("single") || d.includes("singles")) {
          battingStats[player].ab++; battingStats[player].h++;
        } else if (d.includes("walk")) { battingStats[player].bb++; }
        else if (d.includes("struck out")) { battingStats[player].ab++; battingStats[player].k++; }
        else if (d.includes("out")) { battingStats[player].ab++; }
        if (d.includes("rbi") || d.includes("scores")) { battingStats[player].rbi++; }
      });
    }

    const statsRows = Object.entries(battingStats).map(([player, s]) => {
      const avg = s.ab > 0 ? (s.h / s.ab).toFixed(3) : ".000";
      return `${player}: ${s.h}/${s.ab} (${avg}) ${s.rbi} RBI ${s.k > 0 ? s.k + "K" : ""}`;
    }).join("\n");

    const emailBody = `
HONUS GAME REPORT
==================
${gameDate || new Date().toLocaleDateString()}
${awayTeam?.name || "Away"} ${awayTeam?.runs || 0} - ${homeTeam?.name || "Home"} ${homeTeam?.runs || 0}

GAME SUMMARY
------------
${summary}

BATTING STATS
-------------
${statsRows || "No stats captured - add manually"}

PLAY BY PLAY
------------
${plays?.map(p => `${p.time || ""} - ${p.description}`).join("\n") || "No plays recorded"}

---
Generated by Honus AI Coach ⚾
    `.trim();

    res.status(200).json({
      success: true,
      summary,
      emailBody,
      subject: `Honus Game Report - ${teamName || "Your Team"} vs ${opponentName || "Opponent"} - ${gameDate || new Date().toLocaleDateString()}`,
    });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}
