export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();

  const { gameData, plays, teamName, opponentName, gameDate } = req.body;

  try {
    // Generate game summary using Claude
    const homeTeam = gameData?.homeTeam;
    const awayTeam = gameData?.awayTeam;

    const summaryPrompt = `You are Honus, a baseball AI coach. Write a short exciting post-game summary (3-4 sentences) for this game:
${awayTeam?.name || "Away"} ${awayTeam?.runs || 0} - ${homeTeam?.name || "Home"} ${homeTeam?.runs || 0}
Date: ${gameDate || "Today"}
Key plays: ${plays?.slice(-5).map(p => p.description).join(", ") || "No plays recorded"}
Make it enthusiastic and useful for a little league coach!`;

    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5",
        max_tokens: 200,
        messages: [{ role: "user", content: summaryPrompt }],
      }),
    });

    const claudeData = await claudeRes.json();
    const summary = claudeData.content?.[0]?.text || "Great game today!";

    // Build stats table
    const battingStats = {};
    if (plays && plays.length > 0) {
      plays.forEach(play => {
        const desc = play.description || "";
        const playerMatch = desc.match(/^([A-Z]\.\s\w+|\w+\s\w+)/);
        if (!playerMatch) return;
        const player = playerMatch[1];
        if (!battingStats[player]) {
          battingStats[player] = { ab: 0, h: 0, rbi: 0, bb: 0, k: 0 };
        }
        const d = desc.toLowerCase();
        if (d.includes("home run") || d.includes("double") || d.includes("triple") || d.includes("single")) {
          battingStats[player].ab++; battingStats[player].h++;
        } else if (d.includes("walk")) { battingStats[player].bb++; }
        else if (d.includes("struck out")) { battingStats[player].ab++; battingStats[player].k++; }
        else if (d.includes("out")) { battingStats[player].ab++; }
        if (d.includes("rbi") || d.includes("scores")) { battingStats[player].rbi++; }
      });
    }

    const statsRows = Object.entries(battingStats).map(([player, s]) => {
      const avg = s.ab > 0 ? (s.h / s.ab).toFixed(3) : ".000";
      return `<tr><td>${player}</td><td>${s.h}/${s.ab}</td><td>${avg}</td><td>${s.rbi}</td><td>${s.k}</td><td>${s.bb}</td></tr>`;
    }).join("");

    const playByPlay = plays?.map(p => `<tr><td>${p.time || ""}</td><td>${p.description}</td></tr>`).join("") || "<tr><td colspan='2'>No plays recorded</td></tr>";

    // Build HTML email
    const htmlEmail = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; background: #f5f5f5; padding: 20px; }
    .container { background: white; border-radius: 12px; padding: 30px; max-width: 600px; margin: 0 auto; }
    .header { background: #00ff44; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 20px; }
    .header h1 { margin: 0; color: #000; font-size: 24px; }
    .score { font-size: 36px; font-weight: bold; text-align: center; margin: 20px 0; color: #333; }
    .section { margin-bottom: 24px; }
    .section h2 { color: #00cc33; border-bottom: 2px solid #00ff44; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #00ff44; color: #000; padding: 8px; text-align: left; }
    td { padding: 8px; border-bottom: 1px solid #eee; }
    .summary { background: #f9f9f9; padding: 16px; border-left: 4px solid #00ff44; border-radius: 4px; }
    .footer { text-align: center; color: #999; font-size: 12px; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>⚾ HONUS GAME REPORT</h1>
      <p style="margin:0">${gameDate || new Date().toLocaleDateString()}</p>
    </div>

    <div class="score">
      ${awayTeam?.name || "Away"} ${awayTeam?.runs || 0} — ${homeTeam?.name || "Home"} ${homeTeam?.runs || 0}
    </div>

    <div class="section">
      <h2>Game Summary</h2>
      <div class="summary">${summary}</div>
    </div>

    <div class="section">
      <h2>Batting Stats</h2>
      <table>
        <tr><th>Player</th><th>H/AB</th><th>AVG</th><th>RBI</th><th>K</th><th>BB</th></tr>
        ${statsRows || "<tr><td colspan='6'>No stats captured</td></tr>"}
      </table>
    </div>

    <div class="section">
      <h2>Play by Play</h2>
      <table>
        <tr><th>Time</th><th>Play</th></tr>
        ${playByPlay}
      </table>
    </div>

    <div class="footer">Generated by Honus AI Coach ⚾</div>
  </div>
</body>
</html>`;

    // Send via Resend
    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Honus <onboarding@resend.dev>",
        to: ["jcx7816@gmail.com"],
        subject: `⚾ Honus Game Report - ${teamName || "Your Team"} vs ${opponentName || "Opponent"} - ${gameDate || new Date().toLocaleDateString()}`,
        html: htmlEmail,
      }),
    });

    const emailData = await emailRes.json();

    if (!emailRes.ok) {
      throw new Error(emailData.message || "Email failed");
    }

    res.status(200).json({ success: true, message: "Email sent!" });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}
